//dark mode
const darktheme = {
    dark: {
        "--black": "rgb(244, 242, 242)",
        "--white": " #121212",
        "--menu-color": " #000000",
        "--home-c1-color": " #3700b3",
        "--home-c2-color": " #03dac6",
        "--home-c3-color": "rgb(166, 99, 249)",
        "--home-c4-color": " #6200ee",
        "--player-back-color": " #333333",
        "--settings-back-color": " #444444",
        "--about-back-color": " #222222",
        "--menu-text-color": " #ffffff",
        "--player-text-color": " #ffffff",
        "--player-tab-back-color": " #555555",
        "--player-tab-text-color": " #ffffff",
        "--player-tab-active-back-color": " #4b4646",
        "--player-tab-active-text-color": " #ffffff",
        "--settings-head-text-color": " #ffffff",
        "--settings-text-color": "rgb(238, 237, 237)",
        "--about-text-color": " #ffffff",
    },
};

//theme change

const themes = {
    default: {
        "--black": "rgb(46, 36, 30)",
        "--white": " #ffffff",
        "--menu-color": " #463f3a",
        "--menu-text-color": " #ffffff",
        "--home-c1-color": "rgb(125, 97, 89)",
        "--home-c2-color": "rgb(202, 163, 152)",
        "--home-c3-color": " #8a817c",
        "--home-c4-color": " #bcb8b1",
        "--player-back-color": " #f4f3ee",
        "--player-text-color": " #000000",
        "--player-tab-back-color": " #E3CAA5",
        "--player-tab-text-color": " #000000",
        "--player-tab-active-back-color": " #bcb8b1",
        "--player-tab-active-text-color": " #000000",
        "--settings-back-color": " #e0afa0",
        "--settings-head-text-color": " #000000",
        "--settings-text-color": " #000000",
        "--about-back-color": " #AD8B73",
        "--about-text-color": " #302b28",
    },
    ocean: {
        "--black": " #003049",
        "--white": " #eae2b7",
        "--menu-color": " #0077b6",
        "--home-c1-color": "rgb(2, 132, 176)",
        "--home-c2-color": " #00b4d8",
        "--home-c3-color": " #48cae4",
        "--home-c4-color": " #90e0ef",
        "--player-back-color": " #caf0f8",
        "--settings-back-color": " #ade8f4",
        "--about-back-color": " #023e8a",
        "--menu-text-color": " #ffffff",
        "--player-text-color": " #003049",
        "--player-tab-back-color": " #0096c7",
        "--player-tab-text-color": " #003049",
        "--player-tab-active-back-color": "rgb(163, 231, 245)",
        "--player-tab-active-text-color": " #003049",
        "--settings-head-text-color": " #003049",
        "--settings-text-color": " #003049",
        "--about-text-color": " #eae2b7"
    },
    sunset: {
        "--black": " #370617",
        "--white": " #ffba08",
        "--menu-color": " #f48c06",
        "--home-c1-color": " #e85d04",
        "--home-c2-color": " #dc2f02",
        "--home-c3-color": " #9d0208",
        "--home-c4-color": " #6a040f",
        "--player-back-color": "rgb(253, 98, 64)",
        "--settings-back-color": " #c70039",
        "--about-back-color": " #900c3f",
        "--menu-text-color": " #000000",
        "--player-text-color": " #370617",
        "--player-tab-back-color": " #e85d04",
        "--player-tab-text-color": " #370617",
        "--player-tab-active-back-color": " #ff5733",
        "--player-tab-active-text-color": " #370617",
        "--settings-head-text-color": " #370617",
        "--settings-text-color": " #370617",
        "--about-text-color": " #ffba08"
    },
    forest: {
        "--black": " #1b4332",
        "--white": " #fefae0",
        "--menu-color": " #2d6a4f",
        "--home-c1-color": " #40916c",
        "--home-c2-color": " #52b788",
        "--home-c3-color": " #74c69d",
        "--home-c4-color": " #95d5b2",
        "--player-back-color": " #b7e4c7",
        "--settings-back-color": " #d8f3dc",
        "--about-back-color": " #043f2b",
        "--menu-text-color": " #ffffff",
        "--player-text-color": " #1b4332",
        "--player-tab-back-color": " #40916c",
        "--player-tab-text-color": " #fefae0",
        "--player-tab-active-back-color": "rgb(151, 226, 177)",
        "--player-tab-active-text-color": " #1b4332",
        "--settings-head-text-color": " #1b4332",
        "--settings-text-color": " #1b4332",
        "--about-text-color": " #fefae0"
    },
    lavender: {
        "--black": " #3d348b",
        "--white": " #fdf7fa",
        "--menu-color": "rgb(93, 31, 112)",
        "--home-c1-color": "rgb(180, 96, 245)",
        "--home-c2-color": "rgb(237, 178, 246)",
        "--home-c3-color": " #d8b4e2",
        "--home-c4-color": " #b185db",
        "--player-back-color": "rgb(224, 176, 252)",
        "--settings-back-color": " #dee2ff",
        "--about-back-color": " #6a0572",
        "--menu-text-color": " #ffffff",
        "--player-text-color": " #3d348b",
        "--player-tab-back-color": "rgb(176, 84, 247)",
        "--player-tab-text-color": " #3d348b",
        "--player-tab-active-back-color": "rgb(210, 141, 249)",
        "--player-tab-active-text-color": " #3d348b",
        "--settings-head-text-color": " #3d348b",
        "--settings-text-color": " #3d348b",
        "--about-text-color": " #fdf7fa"
    },
    neon: {
        "--black": " #0d0d0d",
        "--white": " #ffffff",
        "--menu-color": " #ff007f",
        "--home-c1-color": " #ff00ff",
        "--home-c2-color": "rgb(250, 46, 0)",
        "--home-c3-color": " #00ff00",
        "--home-c4-color": " #00ffff",
        "--player-back-color": " #ffcc00",
        "--settings-back-color": " #6600ff",
        "--about-back-color": " #ff0066",
        "--menu-text-color": " #000000",
        "--player-text-color": " #0d0d0d",
        "--player-tab-back-color": " #ff007f",
        "--player-tab-text-color": " #ffffff",
        "--player-tab-active-back-color": " #00ffff",
        "--player-tab-active-text-color": " #0d0d0d",
        "--settings-head-text-color": " #ffffff",
        "--settings-text-color": " #ffffff",
        "--about-text-color": " #ffffff"

    },
    royal: {
        "--black": "rgb(59, 58, 0)",
        "--white": " #f0e68c",
        "--menu-color": "rgb(228, 194, 0)",
        "--home-c1-color": " #b8860b",
        "--home-c2-color": "rgb(235, 183, 52)",
        "--home-c3-color": " #f4a460",
        "--home-c4-color": " #ffdead",
        "--player-back-color": "rgb(220, 188, 83)",
        "--settings-back-color": " #b9aa0b",
        "--about-back-color": " #5a3e1b",
        "--menu-text-color": " #000000",
        "--player-text-color": " #1a1a1d",
        "--player-tab-back-color": " #b8860b",
        "--player-tab-text-color": " #1a1a1d",
        "--player-tab-active-back-color": " #d4af37",
        "--player-tab-active-text-color": " #1a1a1d",
        "--settings-head-text-color": " #1a1a1d",
        "--settings-text-color": " #1a1a1d",
        "--about-text-color": " #f0e68c"
    },
    pastel: {
        "--black": " #353a43",
        "--white": " #edf2f4",
        "--menu-color": "rgb(172, 114, 135)",
        "--home-c1-color": "rgb(249, 130, 176)",
        "--home-c2-color": "rgb(46, 149, 240)",
        "--home-c3-color": "rgb(124, 189, 250)",
        "--home-c4-color": "rgb(196, 150, 222)",
        "--player-back-color": "rgb(249, 133, 162)",
        "--settings-back-color": " #ff9a8b",
        "--about-back-color": " #ff758f",
        "--menu-text-color": " #000000",
        "--player-text-color": " #353a43",
        "--player-tab-back-color": " #ffc8dd",
        "--player-tab-text-color": "rgb(53, 57, 65)",
        "--player-tab-active-back-color": "rgb(227, 109, 139)",
        "--player-tab-active-text-color": " #ffffff",
        "--settings-head-text-color": " #353a43",
        "--settings-text-color": " #353a43",
        "--about-text-color": " #edf2f4"
    },
    midnight: {
        "--black": "rgb(22, 19, 48)",
        "--white": " #f4f3ee",
        "--menu-color": " #3d348b",
        "--home-c1-color": " #5d5d81",
        "--home-c2-color": "rgb(48, 48, 75)",
        "--home-c3-color": " #4a4e69",
        "--home-c4-color": " #9a8c98",
        "--player-back-color": "rgb(72, 70, 75)",
        "--settings-back-color": "rgb(68, 74, 47)",
        "--about-back-color": " #1a2a4d",
        "--menu-text-color": " #ffffff",
        "--player-text-color": " #f4f3ee",
        "--player-tab-back-color": " #5d5d81",
        "--player-tab-text-color": " #0a0908",
        "--player-tab-active-back-color": " #22223b",
        "--player-tab-active-text-color": " #ffffff",
        "--settings-head-text-color": "rgb(255, 255, 255)",
        "--settings-text-color": "rgb(255, 255, 255)",
        "--about-text-color": " #f4f3ee"
    },
    retro: {
        "--black": " #2e294e",
        "--white": " #ffefd5",
        "--menu-color": " #ff9f1c",
        "--home-c1-color": " #ff595e",
        "--home-c2-color": " #ffca3a",
        "--home-c3-color": " #8ac926",
        "--home-c4-color": " #1982c4",
        "--player-back-color": " #6a4c93",
        "--settings-back-color": " #c77dff",
        "--about-back-color": " #6d5868",
        "--menu-text-color": " #000000",
        "--player-text-color": " #ffefd5",
        "--player-tab-back-color": " #ffca3a",
        "--player-tab-text-color": " #2e294e",
        "--player-tab-active-back-color": " #ff595e",
        "--player-tab-active-text-color": " #ffffff",
        "--settings-head-text-color": " #2e294e",
        "--settings-text-color": " #2e294e",
        "--about-text-color": " #ffefd5"
    }
};